version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
  db:
    image: postgres:11-alpine
    env_file: .env
