version: '3'
services:
  docker:
    image: docker:18-dind
    privileged: true
  web:
    build: .
    ports:
    - "8080:8080"
    environment:
    - DOCKER_HOST=tcp://docker:2375
    env_file: .env
  db:
    image: postgres:11-alpine
    env_file: .env
